apiVersion: v1
kind: Secret
metadata:
    name: docker-ali-secret
type: kubernetes.io/dockerconfigjson
data:
    .dockerconfigjson: ewoJImF1dGhzIjogewoJCSJodHRwczovL2luZGV4LmRvY2tlci5pby92MS8iOiB7CgkJCSJhdXRoIjogImFYWjVlR3BqT2pKbU9FaHhTVEU1UXlwc2NXTmVWbVJNTWprMCIKCQl9LAoJCSJyZWdpc3RyeS5jbi1oYW5nemhvdS5hbGl5dW5jcy5jb20iOiB7CgkJCSJhdXRoIjogIk1UY3pNVEk1T0RVd01qbEFkVzVpYkc5ck9pTWtPQ1l5U2t0WloxWW1ZbXRPT0RFPSIKCQl9LAoJCSJyZWdpc3RyeS5jbi1zaGVuemhlbi5hbGl5dW5jcy5jb20iOiB7CgkJCSJhdXRoIjogIk1UY3pNVEk1T0RVd01qbEFkVzVpYkc5ck9pTWtPQ1l5U2t0WloxWW1ZbXRPT0RFPSIKCQl9Cgl9Cn0=